name: launchpad
description: The missing dependency injection library for serverpod
version: 0.0.1
repository: https://github.com/thecodebrothers/launchpad

environment:
  sdk: ^3.0.0

dependencies:
  get_it: ^9.0.5
  serverpod: ^2.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
